#!/usr/bin/env python3

import argparse
import sys
import os
from pathlib import Path
import subprocess

class ArgumentCaller():
    
    __version__ = 2.1
    
    def __init__(self):
        print(
"""\033[1m  
  _                    ___             _      _        ___ _  _   _   
 | |   ___ _ _  __ _  | _ \___ __ _ __| |  __(_)_ _ __| _ \ \| | /_\  
 | |__/ _ \ ' \/ _` | |   / -_) _` / _` | / _| | '_/ _|   / .` |/ _ \ 
 |____\___/_||_\__, | |_|_\___\__,_\__,_| \__|_|_| \__|_|_\_|\_/_/ \_\ 
               |___/                                                    

Version: v{}\033[0m""".format(self.__version__))
        
        parser = argparse.ArgumentParser(
            description="Description: CircRNA detection in nanopore data",
            usage='''%(prog)s <command> [args]
            
Available subcommands:
    run                 Main command for finding circRNAs in long read nanopore data
    download-data       Download any required data for references and prepare
    check-installation  Check if all of the required software is available
''')
        parser.add_argument('command', help='Specify which subcommand should be used')
        args = parser.parse_args(sys.argv[1:2])
        command = args.command
        # Correct for inputs with - in the name
        command = command.replace("-","_")
        if not hasattr(self, command):
            print("Unregcognized command")
            parser.print_help()
            sys.exit(1)
        getattr(self, command)()
        
    def run(self):
        parser = argparse.ArgumentParser(
            description="Run the program for detecting circRNAs in nanopore data",
            prog="long_read_circRNA"
            #usage="%(prog)s run sample [options]"
        )
        
        parser.add_argument('sample', help="Provide a sample input .fq.gz file that should be processed by the tool")
        parser.add_argument('--reference-path', default="./data", help="Provide a path for where the reference data is located. Default is './data'.")
        parser.add_argument('--species', default='human', choices=['human', 'mouse'], help="Select which species the sample that is from, and specify which species reference files should be used. Default is set to human.")
        parser.add_argument('--script-path', default="~/long_read_circRNA/scripts", help="Specify where the long_read_circRNA scripts are located. By default it assumes that they are located at '~/long_read_circRNA/scripts'.")
        parser.add_argument('--output-path', '-o', default=".", help="Provide a path for where the output should be saved. Default is the current directory. This will use the output-path and create a directory in that path based on the sample name provided.")
        parser.add_argument('--dry-run', action="store_true", help="Perform all of the input checks without starting the detection scripts")
        parser.add_argument('--keep-temp', action="store_true", help="Keep all of the temporary files.")
        
        args = parser.parse_args(sys.argv[2:])
    
        self.check_installation(args=False)
    
        reference_path = args.reference_path
        species = args.species
        
        # Check if reference_path exists
        if not os.path.exists(reference_path):
            raise Exception("'{}' does not exists! Please make sure that the path is written correctly".format(reference_path))
        # Check if reference_path is a directory:
        if not os.path.isdir(reference_path):
            raise Exception("'{}' is not a directory! Please provide a directory that contains the reference data".format(reference_path))
        # Check if reference_path contains species in the end
        if os.path.basename(reference_path)==species:
            raise Exception("Looks like you have provided the direct path to the species reference directory '{}'. Please simply provide data directory '{}'".format(
                reference_path, os.path.dirname(reference_path)
            ))
        # Check if reference_path + species exists
        if not os.path.exists(os.path.join(reference_path, species)):
            raise Exception("The species subpath {} in the directory {} does not exists".format(species, reference_path))
        # Check if the reference_path + species is a directory
        if not os.path.isdir(os.path.join(reference_path, species)):
            raise Exception("The species subpath {} in the directory {} is not a directory!".format(species, reference_path))
        
        # Check if sample exists
        if not os.path.exists(args.sample):
            raise Exception("Sample file '{}' does not exist!".format(args.sample))
        # Check if sample ends with ".fq.gz"
        if not args.sample.endswith(".fq.gz"):
            raise Exception("Sample file '{}' does not end with '.fq.gz'".format(args.sample))
        # Prepare sample_path and sample_name
        reference_path = str(Path(reference_path).resolve())
        sample_path = str(Path(os.path.dirname(args.sample)).resolve())
        sample_name = os.path.basename(args.sample).replace('.fq.gz', '')
        
        script_path = str(Path(os.path.expanduser(args.script_path)).resolve())
        output_path = str(Path(args.output_path).resolve())
        
        # Check if the script-path exists
        if not os.path.exists(script_path):
            raise Exception("The script path '{}' does not exists! Please point to the location of the scripts directory in the long_read_circRNA path using --script-path".format(script_path))
        # Check if the required scripts are in the script script-path
        target_scripts = ["blat_nanopore_v5.5.sh", "novel_exons_and_alternative_usage_v7.0.sh"]
        for target_script in target_scripts:
            if not os.path.exists(os.path.join(script_path, target_script)):
                raise Exception("'{}' script is not found in the script path '{}'. Are you sure the provided script-path is correct?".format(target_script, script_path))
        
        # Check if the output path exists
        if not os.path.exists(output_path):
            raise Exception("Output_path '{}' does not exist!".format(output_path))
        
        output_path = os.path.join(output_path, sample_name)
        
        print("\033[1mStarting process with the following settings\033[0m")
        print("\033[1m\tSample name:{}\033[0m".format(sample_name))
        print("\033[1m\tReference path: {}\033[0m".format(reference_path))
        print("\033[1m\tSample path: {}\033[0m".format(sample_path))
        print("\033[1m\tSpecies: {}\033[0m".format(species))
        print("\033[1m\tScript-path: {}\033[0m".format(script_path))
        print("\033[1m\tOutput-path: {}\033[0m".format(output_path))
        
        original_directory = os.getcwd()
        
        if not args.dry_run:
            # Main process for circRNA detection
            print("\033[1m")
            subprocess.run(["bash", os.path.join(script_path, "blat_nanopore_v5.5.sh"), 
                            sample_path, sample_name, species, reference_path, script_path, output_path])
            print("\033[0m")
        
            print("\033[1mcircRNA detection has finished\033[0m")
            print("\033[1mStarting the novel exon and alternative usage script\033[0m")
        
            os.chdir(original_directory)
            
            keep_check = {True: "yes", False: "no"}
            
            keep_temp = keep_check[args.keep_temp]
        
            print("\033[1m")
            subprocess.run(["bash", os.path.join(script_path, "novel_exons_and_alternative_usage_v7.0.sh"), 
                        sample_name, species, reference_path, script_path, output_path, keep_temp])
            print("\033[0m")
        
            print("\033[1mLong_read_circRNA has finished!\033[0m")
        else:
            print("\033[1mDry run is complete\033[0m")
        
    
    def download_data(self):
        parser = argparse.ArgumentParser(
            description="Download some test data and required reference data for human and mouse",
            usage="%(prog)s download-data --data-output ./data --test-output ./test_fastq [args]"
        )
        
        parser.add_argument("--data-output", default="./data", help="Where the reference data should be stored")
        parser.add_argument("--test-output", default="./test_fastq", help="Location for the test data")
        parser.add_argument("--skip-human", action="store_true", help="Skip downloading the human reference files")
        parser.add_argument("--skip-mouse", action="store_true", help="Skip downloading the mouse reference files")
        parser.add_argument("--skip-testdata", action="store_true", help="Skip downloading the test data")
        parser.add_argument("--installation-path", default="~/long_read_circRNA", help="Provide a path for where the script is installed. Default is ~/long_read_circRNA")
        args = parser.parse_args(sys.argv[2:])
        
        skip_check = {True: "skip", False: "no"}
        
        skip_human = skip_check[args.skip_human]
        skip_mouse = skip_check[args.skip_mouse]
        skip_testdata = skip_check[args.skip_testdata]
        
        installation_path = str(Path(os.path.expanduser(args.installation_path)).resolve())
        
        # Check if the script-path exists
        if not os.path.exists(installation_path):
            raise Exception("The installation path '{}' does not exists! Please point to the location installed long_read_circRNA path using --installation-path".format(installation_path))
        # Check if the required scripts are in the script script-path
        target_scripts = ["get_required_data.sh"]
        for target_script in target_scripts:
            if not os.path.exists(os.path.join(installation_path, target_script)):
                raise Exception("'{}' script is not found in the installation path '{}'. Are you sure the provided script-path is correct?".format(target_script, installation_path))
        
        call = subprocess.run(["bash", os.path.join(installation_path, "get_required_data.sh"), args.data_output, args.test_output,
                               skip_testdata, skip_human, skip_mouse])
    
    def check_installation(self, args=True):
        if args:
            parser = argparse.ArgumentParser(
                description="Check if environment for running the script is properly setup by checking if all of the required software is available",
                usage="%(prog)s check-installation [args]"
            )
            args = parser.parse_args(sys.argv[2:])
        
        tools = {"bedtools": "bedtools", 
                 "NanoFilt": "NanoFilt -h", 
                 "pblat": "pblat", 
                 "perl": "perl -v",
                 "samtools": "samtools --help"}
        
        failed = False
        warn = False
        
        print()
        
        for tool in tools:
            print("\033[1mChecking for {}\033[0m".format(tool))
            try:
                output = subprocess.run(tools[tool].split(" "), stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=5)
                if output.returncode!=0:
                    print("\033[1;93m\tThere might be a problem with {}\033[0m".format(tool))
                    warn = True
            except FileNotFoundError:
                print("\033[1;91m\tUnable to find {}!\033[0m".format(tool))
                failed = True
            except Exception as e:
                print(e)
        
        if warn:
            print()
            print("\033[1;93mWARNING: There might be a problem with some of the software installed\033[0m")
            print()
        
        if failed:
            print()
            print("\033[1;91mERROR: Some of the required software is missing!\033[0m")
            print()
            sys.exit(1)
        else:
            print()
            print("\033[1mAll of the expected software requirements are present!\033[0m")
            print()        
        
if __name__=="__main__":
    ArgumentCaller()
